_wandb:
    value:
        cli_version: 0.25.0
        e:
            kotnr797ss8nycbaqm9phrcurea0jg8c:
                args:
                    - --epochs
                    - "40"
                    - --batch-size
                    - "64"
                    - --lr
                    - "5e-4"
                    - --dropout
                    - "0.10"
                    - --num-layers
                    - "6"
                    - --warmup-epochs
                    - "5"
                    - --wandb
                    - --wandb-name
                    - txf_lr5e-4_do0.10_L6_ep40
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "56404180992"
                        used: "694964224"
                email: limjiannn@gmail.com
                executable: /scratch/ml8347/conda/envs/neuroinformatics/bin/python
                gpu: NVIDIA L40S
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-4cc7b639-816f-271e-fc28-d39ce3f250db
                host: gl046.hpc.nyu.edu
                memory:
                    total: "540218834944"
                os: Linux-5.14.0-570.12.1.el9_6.x86_64-x86_64-with-glibc2.39
                program: /scratch/ml8347/neuroinformatics/project2/phase2/transformer_decoder/train.py
                python: CPython 3.10.19
                root: /scratch/ml8347/neuroinformatics/project2/phase2/transformer_decoder/sweep_4954587_6
                slurm:
                    array_job_id: "4954587"
                    array_task_count: "8"
                    array_task_id: "6"
                    array_task_max: "7"
                    array_task_min: "0"
                    array_task_step: "1"
                    cluster_name: torch
                    conf: /opt/slurm/data/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: torch_pr_38_tandon_advanced
                    job_cpus_per_node: "4"
                    job_end_time: "1774513437"
                    job_gid: "3940421"
                    job_gpus: "3"
                    job_id: "4963244"
                    job_name: txf_sweep
                    job_nodelist: gl046
                    job_num_nodes: "1"
                    job_partition: l40s_public
                    job_qos: gpu48
                    job_start_time: "1774499037"
                    job_uid: "3940421"
                    job_user: ml8347
                    jobid: "4963244"
                    jobtmp: /state/partition1/job-4963244
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gl046
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /scratch/ml8347/yard_process/s6/BiancaGolden_Portedbras
                    submit_host: torch-login-2.hpc-infra.svc.cluster.local
                    task_pid: "2985512"
                    tasks_per_node: "1"
                    tmpdir: /state/partition1/job-4963244
                    topology_addr: gl046
                    topology_addr_pattern: node
                    tres_per_task: cpu=4
                startedAt: "2026-03-26T04:24:21.026569Z"
                writerId: kotnr797ss8nycbaqm9phrcurea0jg8c
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.19
            "5": 0.25.0
            "8":
                - 2
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 64
d_ff:
    value: 512
d_model:
    value: 256
data_dir:
    value: /scratch/ml8347/neuroinformatics/project2/phase2/transformer_decoder/../kaggle_data
dropout:
    value: 0.1
epochs:
    value: 40
lr:
    value: 0.0005
max_seq_len:
    value: 128
n_params:
    value: 3246210
n_trials:
    value: 59601
nhead:
    value: 4
num_layers:
    value: 6
quick:
    value: false
save_every:
    value: 10
wandb:
    value: true
wandb_name:
    value: txf_lr5e-4_do0.10_L6_ep40
wandb_project:
    value: neuro-p2-phase2
warmup_epochs:
    value: 5
